### COMBAT TYPES ###
COMBAT_TYPE_NONE = 0x1 # Not combat-related.
COMBAT_TYPE_MELEE = 0x2
COMBAT_TYPE_RANGED = 0x3
COMBAT_TYPE_MAGIC = 0x4

### DAMAGE TYPES ###
DAMAGE_TYPE_NONE = 0x1 # No damage
DAMAGE_TYPE_NEUTRAL = 0x2
DAMAGE_TYPE_HEAL = 0x3 # Heals.
DAMAGE_TYPE_MELEE = 0x100
DAMAGE_TYPE_RANGED = 0x200
DAMAGE_TYPE_MAGIC_AIR = 0x300
DAMAGE_TYPE_MAGIC_WATER = 0x301
DAMAGE_TYPE_MAGIC_EARTH = 0x302
DAMAGE_TYPE_MAGIC_FIRE = 0x303
DAMAGE_TYPE_MAGIC_ICE = 0x310
DAMAGE_TYPE_MAGIC_ELECTRIC = 0x311
DAMAGE_TYPE_MAGIC_NATURE = 0x312
DAMAGE_TYPE_MAGIC_HOLY = 0x313
DAMAGE_TYPE_MAGIC_DARK = 0x314
DAMAGE_TYPE_POISON = 0x500

MAGIC_DAMAGE_TYPES = {
    DAMAGE_TYPE_MAGIC_AIR,
    DAMAGE_TYPE_MAGIC_WATER,
    DAMAGE_TYPE_MAGIC_EARTH,
    DAMAGE_TYPE_MAGIC_FIRE,
    DAMAGE_TYPE_MAGIC_ICE,
    DAMAGE_TYPE_MAGIC_ELECTRIC,
    DAMAGE_TYPE_MAGIC_NATURE,
    DAMAGE_TYPE_MAGIC_HOLY,
    DAMAGE_TYPE_MAGIC_DARK,
}
