import imagepaths
import skills
import language
import interactiondata

### INTERACTIVE OBJECT TYPE ID CONSTANTS ###
TYPE_CHARACTER = 0x1
TYPE_MONSTER = 0x2
TYPE_RESOURCE = 0x3
TYPE_ITEM = 0x4
TYPE_OBSTACLE = 0x5
TYPE_CHEST = 0x6


### INTERACTIVE OBJECT ID NUMBERS ###
# SPECIAL IDS ARE 0X1 TO 0XFFFFF
MIN_SPECIAL_ID = 0x000001
MAX_SPECIAL_ID = 0x0FFFFF
PROTAGONIST_ID = 0x000002

# CHARACTER IDS ARE 0X100000 TO 0X1FFFFF
MIN_CHARACTER_ID = 0x100000
MAX_CHARACTER_ID = 0x1FFFFF

# MONSTER IDS ARE 0X200000 TO 0X2FFFFF
MIN_MONSTER_ID = 0x200000
MAX_MONSTER_ID = 0x2FFFFF

# RESOURCE IDS ARE 0X300000 TO 0X3FFFFF
MIN_RESOURCE_ID = 0x300000
MAX_RESOURCE_ID = 0x3FFFFF
HERB_BASIC_ID = 0x300001
ORE_EMPTY_BASIC_ID = 0x300002
TREE_BASIC_ID = 0x300003
TREE_OAK_ID = 0x300004

# ITEM IDS ARE 0X400000 TO 0X4FFFFF
MIN_ITEM_ID = 0x400000
MAX_ITEM_ID = 0x4FFFFF

# OBSTACLE IDS ARE 0X500000 TO 0X5FFFFF
MIN_OBSTACLE_ID = 0x500000
MAX_OBSTACLE_ID = 0x5FFFFF

# CHEST IDS ARE 0X600000 TO 0X6FFFFF
MIN_CHEST_ID = 0x600000
MAX_CHEST_ID = 0x6FFFFF

# MISCELLANEOUS IDS ARE 0x700000 TO 0x7FFFFF
MIN_MISC_ID = 0x700000
ORE_EMPTY_ID = 0x700001
MAX_MISC_ID = 0x7FFFFF

### IMAGE ID NUMBERS ###

### DEFAULT IMAGE ID ###
IMAGE_ID_DEFAULT = 0x001

### OVERWORLD IMAGE TYPE ID NUMBERS ###
OW_IMAGE_ID_DEFAULT = 0x101
OW_IMAGE_ID_FACE_NORTH = 0x102
OW_IMAGE_ID_FACE_EAST = 0x103
OW_IMAGE_ID_FACE_SOUTH = 0x104
OW_IMAGE_ID_FACE_WEST = 0x105
OW_IMAGE_ID_WALK1_NORTH = 0x106
OW_IMAGE_ID_WALK1_EAST = 0x107
OW_IMAGE_ID_WALK1_SOUTH = 0x108
OW_IMAGE_ID_WALK1_WEST = 0x109
OW_IMAGE_ID_WALK2_NORTH = 0x10a
OW_IMAGE_ID_WALK2_EAST = 0x10b
OW_IMAGE_ID_WALK2_SOUTH = 0x10c
OW_IMAGE_ID_WALK2_WEST = 0x10d

### BATTLE MODE IMAGE TYPE ID NUMBERS ###
BATTLE_IMAGE_ID_DEFAULT = 0x201
BATTLE_IMAGE_ID_STAND = 0x202
BATTLE_IMAGE_ID_ATTACK = 0x203
BATTLE_IMAGE_ID_FAINTED = 0x204

### SKILLING IMAGE CATEGORY IDS ###
IMAGE_CATEGORY_SMITHING_SMELTING = 0x101
IMAGE_CATEGORY_SMITHING_ANVIL = 0x102
IMAGE_CATEGORY_HERBLORE_HARVEST = 0x201
IMAGE_CATEGORY_HERBLORE_POTION = 0x202
IMAGE_CATEGORY_CRAFTING_CLOTHES = 0x301
IMAGE_CATEGORY_CRAFTING_GEMS = 0x302
IMAGE_CATEGORY_CRAFTING_WOOD = 0x303
IMAGE_CATEGORY_COOKING = 0x401
IMAGE_CATEGORY_FIREMAKING = 0x501
IMAGE_CATEGORY_CONSTRUCTION = 0x601
IMAGE_CATEGORY_AGILITY_SHORTCUT = 0x701
IMAGE_CATEGORY_AGILITY_OBSTACLE = 0x702
IMAGE_CATEGORY_MINING = 0x801
IMAGE_CATEGORY_FARMING_PLANTING = 0x901
IMAGE_CATEGORY_FARMING_HARVEST = 0x902
IMAGE_CATEGORY_FISHING = 0xa01
IMAGE_CATEGORY_WOODCUTTING = 0xb01
IMAGE_CATEGORY_HUSBANDRY = 0xc01

### SKILLING IMAGE ID NUMBERS ###
IMAGE_ID_SMITHING_SMELTING_1 = 0x10001
IMAGE_ID_SMITHING_SMELTING_2 = 0x10002
IMAGE_ID_HERBLORE_HARVEST_1 = 0x20001
IMAGE_ID_HERBLORE_HARVEST_2 = 0x20001
IMAGE_ID_MINING_1 = 0x80001
IMAGE_ID_MINING_2 = 0x80002
IMAGE_ID_WOODCUTTING_1 = 0xb0001
IMAGE_ID_WOODCUTTING_2 = 0xb0002

# Maps skilling image category IDs
# to a list of image_ids that represent the sequence of sprite images
# to blit when the protagonist performs the particular skill.
# If the list contains in an index, then that represents
# blitting the previous standing overworld image for the Protagonist.
# An empty list means just use the previous standing overworld image.
SKILLING_IMAGE_ID_MAPPING = {
    IMAGE_CATEGORY_SMITHING_SMELTING: [
        IMAGE_ID_SMITHING_SMELTING_1,
        IMAGE_ID_SMITHING_SMELTING_2,
        IMAGE_ID_SMITHING_SMELTING_1,
        None,
    ],
    IMAGE_CATEGORY_SMITHING_ANVIL: [],
    IMAGE_CATEGORY_HERBLORE_HARVEST: [],
    IMAGE_CATEGORY_HERBLORE_POTION: [],
    IMAGE_CATEGORY_CRAFTING_CLOTHES: [],
    IMAGE_CATEGORY_CRAFTING_GEMS: [],
    IMAGE_CATEGORY_CRAFTING_WOOD: [],
    IMAGE_CATEGORY_COOKING: [],
    IMAGE_CATEGORY_FIREMAKING: [],
    IMAGE_CATEGORY_CONSTRUCTION: [],
    IMAGE_CATEGORY_AGILITY_SHORTCUT: [],
    IMAGE_CATEGORY_AGILITY_OBSTACLE: [],
    IMAGE_CATEGORY_MINING: [
        IMAGE_ID_MINING_1,
        IMAGE_ID_MINING_2,
        IMAGE_ID_MINING_1,
        None,
    ],
    IMAGE_CATEGORY_FARMING_PLANTING: [],
    IMAGE_CATEGORY_FARMING_HARVEST: [],
    IMAGE_CATEGORY_FISHING: [],
    IMAGE_CATEGORY_WOODCUTTING: [
        IMAGE_ID_WOODCUTTING_1,
        IMAGE_ID_WOODCUTTING_2,
        IMAGE_ID_WOODCUTTING_1,
        None,
    ],
    IMAGE_CATEGORY_HUSBANDRY: [],
}

## TESTING PROTAG IMAGE PATH DICT
IMAGE_PATH_DICT_PROTAG = {
    OW_IMAGE_ID_DEFAULT: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    OW_IMAGE_ID_FACE_NORTH: imagepaths.PROT_RANGER_F_OW_FACE_NORTH,
    OW_IMAGE_ID_FACE_EAST: imagepaths.PROT_RANGER_F_OW_FACE_EAST,
    OW_IMAGE_ID_FACE_SOUTH: imagepaths.PROT_RANGER_F_OW_FACE_SOUTH,
    OW_IMAGE_ID_FACE_WEST: imagepaths.PROT_RANGER_F_OW_FACE_WEST,
    OW_IMAGE_ID_WALK1_NORTH: imagepaths.PROT_RANGER_F_OW_WALK1_NORTH,
    OW_IMAGE_ID_WALK1_EAST: imagepaths.PROT_RANGER_F_OW_WALK1_EAST,
    OW_IMAGE_ID_WALK1_SOUTH: imagepaths.PROT_RANGER_F_OW_WALK1_SOUTH,
    OW_IMAGE_ID_WALK1_WEST: imagepaths.PROT_RANGER_F_OW_WALK1_WEST,
    OW_IMAGE_ID_WALK2_NORTH: imagepaths.PROT_RANGER_F_OW_WALK2_NORTH,
    OW_IMAGE_ID_WALK2_EAST: imagepaths.PROT_RANGER_F_OW_WALK2_EAST,
    OW_IMAGE_ID_WALK2_SOUTH: imagepaths.PROT_RANGER_F_OW_WALK2_SOUTH,
    OW_IMAGE_ID_WALK2_WEST: imagepaths.PROT_RANGER_F_OW_WALK2_WEST,
    BATTLE_IMAGE_ID_DEFAULT: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_STAND: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_ATTACK: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_FAINTED: imagepaths.PROT_RANGER_F_OW_DEFAULT,
}

### OBJECT DATA FIELDS ###
OBJECT_NAME_INFO_FIELD = 0x1
IMAGE_PATH_DICT_FIELD = 0x2
COLLISION_WIDTH_FIELD = 0x3
COLLISION_HEIGHT_FIELD = 0x4
EXAMINE_INFO_FIELD = 0x5
INTERACTION_ID_FIELD = 0x6

### RESOURCE DATA FIELDS ###
RELATED_SKILL_ID_FIELD = 0x301
REQUIRED_LEVEL_FIELD = 0x302
GAINED_XP_FIELD = 0x303
RESOURCE_ITEM_FIELD = 0x304
RESPAWN_TIME_S_FIELD = 0x305
EXHAUSTION_PROBABILITY_FIELD = 0x306 # Values must be between 0.0 and 1.0

### RESOURCE DATA ###
RESOURCE_DATA = {
    HERB_BASIC_ID: {
        OBJECT_NAME_INFO_FIELD: {
            language.LANG_ENGLISH: "BASIC HERB",
            language.LANG_ESPANOL: "HIERBA BASICA",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.HERB_BASIC_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.HERB_BASIC_PATH,
        },
        COLLISION_WIDTH_FIELD: 1,
        COLLISION_HEIGHT_FIELD: 1,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_HERBLORE,
        REQUIRED_LEVEL_FIELD: 1,
        GAINED_XP_FIELD: 20,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  1,
        EXAMINE_INFO_FIELD: {
            language.LANG_ENGLISH: "Maybe I can pick this herb.",
            language.LANG_ESPANOL: "Tal vez pueda cosechar esta hierba.",
        },
        INTERACTION_ID_FIELD: interactiondata.HERBLORE_GATHER_ID,
        EXHAUSTION_PROBABILITY_FIELD: 0.3,
    },
    ORE_EMPTY_BASIC_ID: { # TODO make this a generic interactive object?
        OBJECT_NAME_INFO_FIELD: {
            language.LANG_ENGLISH: "EMPTY ORE",
            language.LANG_ESPANOL: "VENA AGOTADA",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.ORE_EMPTY_BASIC_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.ORE_EMPTY_BASIC_PATH,
        },
        COLLISION_WIDTH_FIELD: 1,
        COLLISION_HEIGHT_FIELD: 1,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_MINING,
        REQUIRED_LEVEL_FIELD: 1,
        GAINED_XP_FIELD: 20,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  None,
        EXAMINE_INFO_FIELD: {
            language.LANG_ENGLISH: "This ore is empty",
            language.LANG_ESPANOL: "Esta vena esta agotada",
        },
        INTERACTION_ID_FIELD: interactiondata.MINE_ROCK_ID,
    },
    TREE_BASIC_ID: {
        OBJECT_NAME_INFO_FIELD: {
            language.LANG_ENGLISH: "TREE",
            language.LANG_ESPANOL: "ARBOL",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.TREE_BASIC_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.TREE_BASIC_PATH,
        },
        COLLISION_WIDTH_FIELD: 2,
        COLLISION_HEIGHT_FIELD: 1,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_WOODCUTTING,
        REQUIRED_LEVEL_FIELD: 1,
        GAINED_XP_FIELD: 20,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  1,
        EXAMINE_INFO_FIELD: {
            language.LANG_ENGLISH: "It's just a tree. Maybe I can cut it down.",
            language.LANG_ESPANOL: "Es solo un arbol. Tal vez pueda talarlo.",
        },
        INTERACTION_ID_FIELD: interactiondata.CHOP_TREE_ID,
        EXHAUSTION_PROBABILITY_FIELD: 1.0,
    },
    TREE_OAK_ID: {
        OBJECT_NAME_INFO_FIELD: {
            language.LANG_ENGLISH: "OAK TREE",
            language.LANG_ESPANOL: "ROBLE",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.TREE_OAK_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.TREE_OAK_PATH,
        },
        COLLISION_WIDTH_FIELD: 2,
        COLLISION_HEIGHT_FIELD: 1,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_WOODCUTTING,
        REQUIRED_LEVEL_FIELD: 10,
        GAINED_XP_FIELD: 50,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  10,
        EXAMINE_INFO_FIELD: {
            language.LANG_ENGLISH: "What a magnificent oak. Maybe I can cut it down.",
            language.LANG_ESPANOL: "Que roble tan maravilloso! Tal vez pueda talarlo.",
        },
        INTERACTION_ID_FIELD: interactiondata.CHOP_TREE_ID,
        EXHAUSTION_PROBABILITY_FIELD: 0.2,
    },
}
