import imagepaths
import skills
import language

### INTERACTIVE OBJECT TYPE ID CONSTANTS ###
TYPE_CHARACTER = 0x1
TYPE_MONSTER = 0x2
TYPE_RESOURCE = 0x3
TYPE_ITEM = 0x4
TYPE_OBSTACLE = 0x5
TYPE_CHEST = 0x6

### DEFAULT IMAGE ID ###
IMAGE_ID_DEFAULT = 0x001

### OVERWORLD IMAGE TYPE ID NUMBERS ###
OW_IMAGE_ID_DEFAULT = 0x101
OW_IMAGE_ID_FACE_NORTH = 0x102
OW_IMAGE_ID_FACE_EAST = 0x103
OW_IMAGE_ID_FACE_SOUTH = 0x104
OW_IMAGE_ID_FACE_WEST = 0x105
OW_IMAGE_ID_WALK1_NORTH = 0x106
OW_IMAGE_ID_WALK1_EAST = 0x107
OW_IMAGE_ID_WALK1_SOUTH = 0x108
OW_IMAGE_ID_WALK1_WEST = 0x109
OW_IMAGE_ID_WALK2_NORTH = 0x10a
OW_IMAGE_ID_WALK2_EAST = 0x10b
OW_IMAGE_ID_WALK2_SOUTH = 0x10c
OW_IMAGE_ID_WALK2_WEST = 0x10d

### BATTLE MODE IMAGE TYPE ID NUMBERS ###
BATTLE_IMAGE_ID_DEFAULT = 0x201
BATTLE_IMAGE_ID_STAND = 0x202
BATTLE_IMAGE_ID_ATTACK = 0x203
BATTLE_IMAGE_ID_FAINTED = 0x204

### INTERACTIVE OBJECT ID NUMBERS ###
# SPECIAL IDS ARE 0X1 TO 0XFFFFF
MIN_SPECIAL_ID = 0x000001
MAX_SPECIAL_ID = 0x0FFFFF
PROTAGONIST_ID = 0x000002

# CHARACTER IDS ARE 0X100000 TO 0X1FFFFF
MIN_CHARACTER_ID = 0x100000
MAX_CHARACTER_ID = 0x1FFFFF

# MONSTER IDS ARE 0X200000 TO 0X2FFFFF
MIN_MONSTER_ID = 0x200000
MAX_MONSTER_ID = 0x2FFFFF

# RESOURCE IDS ARE 0X300000 TO 0X3FFFFF
MIN_RESOURCE_ID = 0x300000
MAX_RESOURCE_ID = 0x3FFFFF
HERB_BASIC_ID = 0x300001
ORE_EMPTY_BASIC_ID = 0x300002
TREE_BASIC_ID = 0x300003
TREE_OAK_ID = 0x300004

# ITEM IDS ARE 0X400000 TO 0X4FFFFF
MIN_ITEM_ID = 0x400000
MAX_ITEM_ID = 0x4FFFFF

# OBSTACLE IDS ARE 0X500000 TO 0X5FFFFF
MIN_OBSTACLE_ID = 0x500000
MAX_OBSTACLE_ID = 0x5FFFFF

# CHEST IDS ARE 0X600000 TO 0X6FFFFF
MIN_CHEST_ID = 0x600000
MAX_CHEST_ID = 0x6FFFFF

# MISCELLANEOUS IDS ARE 0x700000 TO 0x7FFFFF
MIN_MISC_ID = 0x700000
ORE_EMPTY_ID = 0x700001
MAX_MISC_ID = 0x7FFFFF

## TESTING PROTAG IMAGE PATH DICT
IMAGE_PATH_DICT_PROTAG = {
    OW_IMAGE_ID_DEFAULT: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    OW_IMAGE_ID_FACE_NORTH: imagepaths.PROT_RANGER_F_OW_FACE_NORTH,
    OW_IMAGE_ID_FACE_EAST: imagepaths.PROT_RANGER_F_OW_FACE_EAST,
    OW_IMAGE_ID_FACE_SOUTH: imagepaths.PROT_RANGER_F_OW_FACE_SOUTH,
    OW_IMAGE_ID_FACE_WEST: imagepaths.PROT_RANGER_F_OW_FACE_WEST,
    OW_IMAGE_ID_WALK1_NORTH: imagepaths.PROT_RANGER_F_OW_WALK1_NORTH,
    OW_IMAGE_ID_WALK1_EAST: imagepaths.PROT_RANGER_F_OW_WALK1_EAST,
    OW_IMAGE_ID_WALK1_SOUTH: imagepaths.PROT_RANGER_F_OW_WALK1_SOUTH,
    OW_IMAGE_ID_WALK1_WEST: imagepaths.PROT_RANGER_F_OW_WALK1_WEST,
    OW_IMAGE_ID_WALK2_NORTH: imagepaths.PROT_RANGER_F_OW_WALK2_NORTH,
    OW_IMAGE_ID_WALK2_EAST: imagepaths.PROT_RANGER_F_OW_WALK2_EAST,
    OW_IMAGE_ID_WALK2_SOUTH: imagepaths.PROT_RANGER_F_OW_WALK2_SOUTH,
    OW_IMAGE_ID_WALK2_WEST: imagepaths.PROT_RANGER_F_OW_WALK2_WEST,
    BATTLE_IMAGE_ID_DEFAULT: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_STAND: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_ATTACK: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_FAINTED: imagepaths.PROT_RANGER_F_OW_DEFAULT
}

### OBJECT DATA FIELDS ###
OBJECT_NAME_FIELD = 0x1
IMAGE_PATH_DICT_FIELD = 0x2
COLLISION_WIDTH_FIELD = 0x3
COLLISION_HEIGHT_FIELD = 0x4

### RESOURCE DATA FIELDS ###
RELATED_SKILL_ID_FIELD = 0x301
REQUIRED_LEVEL_FIELD = 0x302
GAINED_XP_FIELD = 0x303
RESOURCE_ITEM_FIELD = 0x304
RESPAWN_TIME_S_FIELD = 0x305

### RESOURCE DATA ###
RESOURCE_DATA = {
    HERB_BASIC_ID: {
        OBJECT_NAME_FIELD: {
            language.LANG_ENGLISH: "BASIC HERB",
            language.LANG_ESPANOL: "HIERBA BASICA",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.HERB_BASIC_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.HERB_BASIC_PATH,
        },
        COLLISION_WIDTH_FIELD: 1,
        COLLISION_HEIGHT_FIELD: 1,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_HERBLORE,
        REQUIRED_LEVEL_FIELD: 1,
        GAINED_XP_FIELD: 20,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  1,
    },
    ORE_EMPTY_BASIC_ID: { # TODO make this a generic interactive object?
        OBJECT_NAME_FIELD: {
            language.LANG_ENGLISH: "EMPTY ORE",
            language.LANG_ESPANOL: "VENA AGOTADA",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.ORE_EMPTY_BASIC_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.ORE_EMPTY_BASIC_PATH,
        },
        COLLISION_WIDTH_FIELD: 1,
        COLLISION_HEIGHT_FIELD: 1,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_MINING,
        REQUIRED_LEVEL_FIELD: 1,
        GAINED_XP_FIELD: 20,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  None,
    },
    TREE_BASIC_ID: {
        OBJECT_NAME_FIELD: {
            language.LANG_ENGLISH: "TREE",
            language.LANG_ESPANOL: "ARBOL",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.TREE_BASIC_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.TREE_BASIC_PATH,
        },
        COLLISION_WIDTH_FIELD: 1,
        COLLISION_HEIGHT_FIELD: 1,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_WOODCUTTING,
        REQUIRED_LEVEL_FIELD: 1,
        GAINED_XP_FIELD: 20,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  1,
    },
    TREE_OAK_ID: {
        OBJECT_NAME_FIELD: {
            language.LANG_ENGLISH: "OAK TREE",
            language.LANG_ESPANOL: "ROBLE",
        },
        IMAGE_PATH_DICT_FIELD: {
            IMAGE_ID_DEFAULT: imagepaths.TREE_OAK_PATH,
            OW_IMAGE_ID_DEFAULT: imagepaths.TREE_OAK_PATH,
        },
        COLLISION_WIDTH_FIELD: 2,
        COLLISION_HEIGHT_FIELD: 2,
        RELATED_SKILL_ID_FIELD: skills.SKILL_ID_WOODCUTTING,
        REQUIRED_LEVEL_FIELD: 10,
        GAINED_XP_FIELD: 50,
        RESOURCE_ITEM_FIELD: None,
        RESPAWN_TIME_S_FIELD:  10,
    },
}
