import imagepaths

### INTERACTIVE OBJECT TYPE ID CONSTANTS ###
TYPE_CHARACTER = 0x1
TYPE_MONSTER = 0x2
TYPE_RESOURCE = 0x3
TYPE_ITEM = 0x4
TYPE_OBSTACLE = 0x5
TYPE_CHEST = 0x6

### OVERWORLD IMAGE TYPE ID NUMBERS ###
OW_IMAGE_ID_DEFAULT = 0x0
OW_IMAGE_ID_FACE_NORTH = 0x1
OW_IMAGE_ID_FACE_EAST = 0x2
OW_IMAGE_ID_FACE_SOUTH = 0x3
OW_IMAGE_ID_FACE_WEST = 0x4
OW_IMAGE_ID_WALK1_NORTH = 0x5
OW_IMAGE_ID_WALK1_EAST = 0x6
OW_IMAGE_ID_WALK1_SOUTH = 0x7
OW_IMAGE_ID_WALK1_WEST = 0x8
OW_IMAGE_ID_WALK2_NORTH = 0x9
OW_IMAGE_ID_WALK2_EAST = 0xa
OW_IMAGE_ID_WALK2_SOUTH = 0xb
OW_IMAGE_ID_WALK2_WEST = 0xc

### BATTLE MODE IMAGE TYPE ID NUMBERS ###
BATTLE_IMAGE_ID_DEFAULT = 0xd
BATTLE_IMAGE_ID_STAND = 0xe
BATTLE_IMAGE_ID_ATTACK = 0xf
BATTLE_IMAGE_ID_FAINTED = 0x10

### INTERACTIVE OBJECT ID NUMBERS ###
# SPECIAL IDS ARE 0X1 TO 0XFFFFF
MIN_SPECIAL_ID = 0x1
MAX_SPECIAL_ID = 0xFFFFF
PROTAGONIST_ID = 0x2

# CHARACTER IDS ARE 0X100000 TO 0X1FFFFF
MIN_CHARACTER_ID = 0x100000
MAX_CHARACTER_ID = 0x1FFFFF

# MONSTER IDS ARE 0X200000 TO 0X2FFFFF
MIN_MONSTER_ID = 0x200000
MAX_MONSTER_ID = 0x2FFFFF

# RESOURCE IDS ARE 0X300000 TO 0X3FFFFF
MIN_RESOURCE_ID = 0x300000
MAX_RESOURCE_ID = 0x3FFFFF
HERB_BASIC_ID = 0x300001
ORE_EMPTY_BASIC_ID = 0x300002
TREE_BASIC_ID = 0x300003
TREE_OAK_ID = 0x300004

# ITEM IDS ARE 0X400000 TO 0X4FFFFF
MIN_ITEM_ID = 0x400000
MAX_ITEM_ID = 0x4FFFFF

# OBSTACLE IDS ARE 0X500000 TO 0X5FFFFF
MIN_OBSTACLE_ID = 0x500000
MAX_OBSTACLE_ID = 0x5FFFFF

# CHEST IDS ARE 0X600000 TO 0X6FFFFF
MIN_CHEST_ID = 0x600000
MAX_CHEST_ID = 0x6FFFFF

## TESTING PROTAG IMAGE PATH DICT
IMAGE_PATH_DICT_PROTAG = {
    OW_IMAGE_ID_DEFAULT: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    OW_IMAGE_ID_FACE_NORTH: imagepaths.PROT_RANGER_F_OW_FACE_NORTH,
    OW_IMAGE_ID_FACE_EAST: imagepaths.PROT_RANGER_F_OW_FACE_EAST,
    OW_IMAGE_ID_FACE_SOUTH: imagepaths.PROT_RANGER_F_OW_FACE_SOUTH,
    OW_IMAGE_ID_FACE_WEST: imagepaths.PROT_RANGER_F_OW_FACE_WEST,
    OW_IMAGE_ID_WALK1_NORTH: imagepaths.PROT_RANGER_F_OW_WALK1_NORTH,
    OW_IMAGE_ID_WALK1_EAST: imagepaths.PROT_RANGER_F_OW_WALK1_EAST,
    OW_IMAGE_ID_WALK1_SOUTH: imagepaths.PROT_RANGER_F_OW_WALK1_SOUTH,
    OW_IMAGE_ID_WALK1_WEST: imagepaths.PROT_RANGER_F_OW_WALK1_WEST,
    OW_IMAGE_ID_WALK2_NORTH: imagepaths.PROT_RANGER_F_OW_WALK2_NORTH,
    OW_IMAGE_ID_WALK2_EAST: imagepaths.PROT_RANGER_F_OW_WALK2_EAST,
    OW_IMAGE_ID_WALK2_SOUTH: imagepaths.PROT_RANGER_F_OW_WALK2_SOUTH,
    OW_IMAGE_ID_WALK2_WEST: imagepaths.PROT_RANGER_F_OW_WALK2_WEST,
    BATTLE_IMAGE_ID_DEFAULT: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_STAND: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_ATTACK: imagepaths.PROT_RANGER_F_OW_DEFAULT,
    BATTLE_IMAGE_ID_FAINTED: imagepaths.PROT_RANGER_F_OW_DEFAULT
}
