import imagepaths

### TRANSPORTATION FLAGS ###
NO_TRANSPORT_F = 0x0
WALKABLE_F = 0x1
CANOEABLE_F = 0x2
SAILABLE_F = 0x4
FLYABLE_F = 0x8

### TILE ID NUMBERS ###
TILE_DEFAULT_ID = 0x1
TILE_GRASS_1_ID = 0x100
TILE_GRASS_2_ID = 0x101
TILE_GRASS_PLAIN_ID = 0x102
TILE_GRASS_FLOWERS_ID = 0x103
TILE_WATER_NORMAL_1_ID = 0x200
TILE_WATER_NORMAL_2_ID = 0x201
TILE_WATER_NORMAL_3_ID = 0x202
TILE_WATER_NORMAL_4_ID = 0x203
TILE_WATER_NORMAL_5_ID = 0x204
TILE_WATER_NORMAL_6_ID = 0x205
TILE_WATER_NORMAL_7_ID = 0x206
TILE_WATER_NORMAL_8_ID = 0x207
TILE_WATER_NORMAL_9_ID = 0x208
TILE_SAND_ID = 0x300

### TILE FACTORY DATA ###
TILE_IMAGE_PATH_FIELD = 0x1
TILE_ALLOWED_TRANSPORT_FIELD = 0x2

TILE_DATA = {
    TILE_DEFAULT_ID: {
        TILE_IMAGE_PATH_FIELD: imagepaths.TILE_DEFAULT_PATH,
        TILE_ALLOWED_TRANSPORT_FIELD: NO_TRANSPORT_F
    },
    TILE_GRASS_1_ID: {
        TILE_IMAGE_PATH_FIELD: imagepaths.TILE_GRASS_1_PATH
    },
    TILE_GRASS_2_ID: {
        TILE_IMAGE_PATH_FIELD: imagepaths.TILE_GRASS_2_PATH
    },
    TILE_GRASS_PLAIN_ID: {
        TILE_IMAGE_PATH_FIELD: imagepaths.TILE_GRASS_PLAIN_PATH
    },
    TILE_GRASS_FLOWERS_ID: {
        TILE_IMAGE_PATH_FIELD: imagepaths.TILE_GRASS_FLOWERS_PATH
    },
    TILE_WATER_NORMAL_1_ID: {
        TILE_IMAGE_PATH_FIELD: imagepaths.TILE_WATER_NORMAL_1_PATH,
        TILE_ALLOWED_TRANSPORT_FIELD: (FLYABLE_F | CANOEABLE_F)
    },
    TILE_SAND_ID: {
        TILE_IMAGE_PATH_FIELD: imagepaths.TILE_SAND_PATH
    }
}
